spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aluga_ai
    username: root
    password: stalker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
storage:
  location: /home/joao/Documents/aluga_ai
server:
  port: 25565