spring:
  datasource:
    url: jdbc:mysql://localhost:3306/aluga_ai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: luciano.coelhho@gmail.com
    password: jlrz mefy qwbi nufe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
storage:
  location: C:\Users\Lucas\OneDrive\Documentos\pastaVaziaSpring
server:
  port: 25565
